from enum import Enum

class LinkedInAPICapability(Enum):
    SEARCH_EMPLOYEES_BY_DOMAIN = 0
    SEARCH_EMPLOYEES_BY_SOCIAL_NETWORK = 1
    EXPORT_PROFILE_LIST = 2
    PARSE_EXPORTED_PROFILE_LIST = 3
